ALTER TABLE articles
ADD COLUMN reading_time INT DEFAULT NULL,
ADD COLUMN topic_classification VARCHAR(100) DEFAULT NULL,
ADD COLUMN recommendation_score DOUBLE DEFAULT NULL,
ADD COLUMN trending_score DOUBLE DEFAULT NULL,
ADD COLUMN ai_confidence DOUBLE DEFAULT NULL,
ADD COLUMN processing_status VARCHAR(20) DEFAULT 'PENDING',
ADD COLUMN processed_at TIMESTAMP DEFAULT NULL;
